name: My Super App continuous Delivery
on:
  push:
    branches:
      - 'main'
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Build Application
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=$ECR_REG -DskipTests=true
        env:
          ECR_REG: ${{ vars.ECR_REGISTRY }}
      - run: echo "This job's status is ${{ job.status }}."