name: My Super App continuous Delivery
on:
  push:
    branches:
      - 'main'
permissions:
  id-token: write
  contents: read
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Application
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=$ECR_REG -DskipTests=true
        env:
          ECR_REG: ${{ vars.ECR_REGISTRY }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::345594592283:role/GitHubActionsECR
          aws-region: eu-west-3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Docker push
        run: docker push $ECR_REG:latest
        env:
          ECR_REG: ${{ vars.ECR_REGISTRY }}