name: My Super App continuous Delivery
on:
  push:
    branches:
      - 'main'
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Application
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=$ECR_REG -DskipTests=true
        env:
          ECR_REG: ${{ vars.ECR_REGISTRY }}
      - run: echo "This job's status is ${{ job.status }}."