name: My Super App Continuous Integration
run-name: Job started by ${{ github.actor }}
on: [push]
jobs:
  Maven-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: pwd
      - name: run tests
        run: mvn clean test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            target/surefire-reports/**/*.xml
      - name: Build Application
        run: mvn clean install spring-boot:build-image
      - run: echo "This job's status is ${{ job.status }}."
